version: '3.5'
services: 
  db:
    image: postgres:alpine
    environment: 
    - 'POSTGRES_DB=postgres'
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_PASSWORD=postgres'
    volumes: 
      - ${PWD}/db-init:/docker-entrypoint-initdb.d
    networks: 
      - sam

networks: 
  sam:
    external: true